Enhancement: PartitionGeometry
BlueQuartzSoftware/DREAM3D pull request #1005
Opened 2022-10-05 20:09 UTC by joeykleingers

* New partitioning mode that allows using an existing partitioning scheme.
* Feature attribute matrix created with the appropriate size.
* Edge case fix: if a user tries to partition a node geometry in Basic or Bounding Box mode where the geometry vertices or bounding box vertices are in a plane, the filter will error out correctly.

2022-10-05 21:52 UTC, imikejackson requested changes

2022-10-05 21:52 UTC, imikejackson commented on Source/Plugins/Reconstruction/ReconstructionFilters/PartitionGeometry.h
> +  template <typename G>
Stylisticly, I would like to see ```template <typename GeomType>``` which gives the developer some indication for what type of object should be passed in.

2022-10-05 21:52 UTC, imikejackson commented on Source/Plugins/Reconstruction/ReconstructionFilters/PartitionGeometry.h
> +
we should strive for some basic docs for what these functions do.

2022-10-06 17:37 UTC, joeykleingers commented
Mike and I discussed this PR and he would like a vertex mask option added to this filter.

2022-11-14 15:13 UTC, jmarquisbq approved these changes

2022-11-14 15:22 UTC, merged