Feature/python wrapping
BlueQuartzSoftware/DREAM3D pull request #864
Opened 2019-01-17 15:36 UTC by imikejackson

2019-01-17 15:51 UTC, mmarineBlueQuartz commented on Source/Plugins/OrientationAnalysis/OrientationAnalysisFilters/EbsdToH5Ebsd.h
> +    PYB11_PROPERTY(int64_t ZEndIndex READ getZEndIndex WRITE setZEndIndex)
Formatting is off on two of these.

2019-01-17 15:52 UTC, mmarineBlueQuartz commented on Source/Plugins/OrientationAnalysis/OrientationAnalysisFilters/INLWriter.h
> +	PYB11_PROPERTY(QString OutputFile READ getOutputFile WRITE setOutputFile)
Indentation

2019-01-17 15:53 UTC, mmarineBlueQuartz commented on Source/Plugins/Reconstruction/ReconstructionFilters/MergeTwins.h
> +	PYB11_PROPERTY(bool UseNonContiguousNeighbors READ getUseNonContiguousNeighbors WRITE setUseNonContiguousNeighbors)
This entire chunk has an extra indentation

2019-01-17 15:54 UTC, mmarineBlueQuartz commented on Source/Plugins/Statistics/StatisticsFilters/FindSurfaceAreaToVolume.h
> +	PYB11_PROPERTY(bool CalculateSphericity READ getCalculateSphericity WRITE setCalculateSphericity)
Indentation

2019-01-17 15:54 UTC, mmarineBlueQuartz commented on Source/Plugins/SyntheticBuilding/SyntheticBuildingFilters/PackPrimaryPhases.h
> +	PYB11_PROPERTY(QString OutputCellEnsembleAttributeMatrixName READ getOutputCellEnsembleAttributeMatrixName WRITE setOutputCellEnsembleAttributeMatrixName)
Indentation

2019-01-17 15:55 UTC, mmarineBlueQuartz requested changes
Fix a few indentation formatting, and this will be good.

2019-01-18 16:00 UTC, mmarineBlueQuartz approved these changes
This looks good.

2019-01-18 16:07 UTC, joeykleingers approved these changes
Looks good to me.

2019-02-16 13:56 UTC, merged